### ISSUE TITLE
error in importing 'pyIFD.ADQ2'

### ISSUE THREAD

**Issue by mohammedkw11** [EldritchJS/pyIFD#13]
Hey Mr. Eldritch,

I tried to run your project and when I run the second command $pdoc3... I received this error:

`ImportError: Error importing 'pyIFD.ADQ2': ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

What is the issue do you think?

Thanks in advance!

**Comment by EldritchJS** [comment]
Hi, it sounds like an issue with the JPEGIO library compatibility with your version of numpy. Couple things:

1. What platform are you running this on?
2. How did you install the pyIFD? (e.g. pip, source, etc.)
3. Assuming you used pip, what version of JPEGIO numpy does `pip freeze` indicate you're using?

**Comment by mohammedkw11** [comment]
> Hi, it sounds like an issue with the JPEGIO library compatibility with your version of numpy. Couple things:
> 
> 1. What platform are you running this on?
> 2. How did you install the pyIFD? (e.g. pip, source, etc.)
> 3. Assuming you used pip, what version of JPEGIO numpy does `pip freeze` indicate you're using?

1. macOS Monterey
2. pip install ...
3. jpegio==0.2.8

Thanks!

**Comment by EldritchJS** [comment]
I just tried installing on a mac with Monterey using pip install. I'm able to run the test case in this repo per the following:

`git clone https://github.com/EldritchJS/pyIFD`
`cd pyIFD/tests`
`python validate_algo.py --algorithms ADQ2 --imagefilename data/168_image.jpg --groundtruthfilesrootdir data`

Which passes on my system. As a baseline can you check if this works on your system?

**Comment by mohammedkw11** [comment]
Thank you! It works now but I do have a question.

how do you calculate the .mat for the images in order for validation. In other word, I want to generate .mat for another images, then manipulate them and then check the validation with the orignal to compare the robustness of each algorithm

**Comment by EldritchJS** [comment]
Unfortunately the way those .mat files were generated was with closed source from the original authors of the algorithms, which our collaborators were given access to. That's the rub with this project: we wanted to bring this image forgery detection functionality to everyone via an open source cross-platform library in Python, but had to validate it off the closed source one!

As your original issue seems to have been resolved, I am going to close the issue at this point.
